### ISSUE TITLE
Stuck updating catalog 3%

### ISSUE THREAD

**Issue by Lennart1978** [reactorcoder/tinyappscatalogmanager#1]
I compiled tinyappscatalogmanager for Linux Amd64. I have a problem, it stucks at 3% when updating catalog ?!

**Comment by marinsagovac** [comment]
Please try to add permissions folder up of current projects. It should create a folder screenshots and download all lists of images. Please run via console and paste what happen when stuck on 3%.

**Comment by Lennart1978** [comment]
Thanks. I added permissions to the folder and now it works.
